kemtek/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth import views as auth_views

from django.views.generic import RedirectView


urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/lab_reports/login')),
    url(r'lab_reports/', include('lab_reports.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^login$', RedirectView.as_view(url='/lab_reports/login')),
    url(r'^logout$', auth_views.logout, {'template_name': 'registration/logout.html'}, name="logout"),
]

lab_reports/urls.py
from django.conf.urls import url
from django.contrib import admin

from django.contrib.auth import views as auth_views

from wkhtmltopdf.views import PDFTemplateView

from . import views

app_name = "lab_reports"
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),

    url(r'^login$', views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    
    url(r'^site/(?P<pk>[0-9]+)/$', views.SiteView.as_view(), name='site-detail'),
    url(r'^sites$', views.SiteListView.as_view(), name='site-list'),
    
    url(r'^report/(?P<pk>[0-9]+)/$', views.ReportView.as_view(), name='report-detail'),
    url(r'^report/add/(?P<site_id>[0-9]+)/$', views.ReportCreate.as_view(), name='report-add'),
    url(r'^report/edit/(?P<report_id>[0-9]+)/remarks/$', views.ReportEditRemarksView.as_view(), name='report-edit-remarks'),
    url(r'^report/delete/(?P<pk>[0-9]+)/$', views.ReportDelete.as_view(), name='report-delete'),
    url(r'^report/pdf/(?P<report_id>[0-9]+)/$', views.ReportPrintView.as_view(), name='report-pdf'),
    url(r'^report/pdf/(?P<report_id>[0-9]+)/download$', views.ReportDownloadView.as_view(), name='report-download'),
    
    url(r'^test/add/(?P<report_id>[0-9]+)/$', views.TestAddView.as_view(), name='test-add'),
    url(r'^test/edit/(?P<test_id>[0-9]+)/$', views.TestEdit.as_view(), name='test-edit'),
    url(r'^test/delete/(?P<pk>[0-9]+)/$', views.TestDelete.as_view(), name='test-delete'),
]


lab_reports/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse

# Create your models here.
class TimeTrackable(models.Model):
    date_updated = models.DateTimeField('date updated', auto_now=True)
    date_created = models.DateTimeField('date created', auto_now_add=True)

    class Meta:
        abstract = True

class Site(TimeTrackable):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    location = models.CharField(max_length=200)

    def __str__(self):
        return "{}-{}".format(self.description, self.location)

    def get_reports(self):
        return Report.objects.filter(site_id=self.id)

    def get_location_font_color(self):
        if "hot" in self.location.lower():
            return 'red'
        elif "chilled" in self.location.lower():
            return 'blue'
        else:
            return 'black'

    def get_location_icon(self):
        if "hot" in self.location.lower():
            return 'fa fa-fire fa-lg'
        elif "chilled" in self.location.lower():
            return 'fa fa-snowflake-o fa-lg'
        else:
            return 'fa fa-tint fa-lg'

class ReportManager(models.Manager):
    def recent_reports(self, number):
        return self.order_by('-date_created')[:number]


class Report(TimeTrackable):
    site = models.ForeignKey(Site, related_name="%(app_label)s_%(class)s_site")
    remarks = models.TextField()
    report_date = models.DateTimeField()

    objects = ReportManager()

    def __str__(self):
        """ returns string of Report """
        return "{} {}".format(self.report_date, self.site)

    def get_tests(self):
        """ gets all tests belonging to this report """
        return Test.objects.filter(report_id=self.id)

    def get_site(self):
        """ returns site of report """
        return Site.objects.get(id=self.site.id)

    def wipe_tests(self):
        """ deletes all associated tests """
        Test.objects.filter(report_id=self.id).delete()


class Test(TimeTrackable):
    
    DESCRIPTION_CHOICES = (
    ('PAK', 'P Alkalinity'),
    ('MAK', 'M Alkalinity'),
    ('CHL', 'Chlorides'),
    ('HRD', 'Hardness'),
    ('NIT', 'Nitrite'),
    ('PHO', 'Phosphate'),
    ('SUL', 'Sulfite'),
    ('PH', 'Ph'),
    ('SUS', 'Suspended Solids'),
    )

    report = models.ForeignKey(Report, related_name="%(app_label)s_%(class)s_report")
    description = models.CharField(max_length=3, choices=DESCRIPTION_CHOICES)
    measurement = models.CharField(max_length=200)
    residuals = models.CharField(max_length=200)
    parameters = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return "{} {}".format(self.report, self.description)

lab_reports/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm


from .models import Test, Report

class TestForm(forms.ModelForm):

    class Meta:
        model = Test
        fields = ('description', 'measurement', 'residuals', 'parameters')

class ReportDateForm(forms.ModelForm):
    report_date = forms.DateField(widget=forms.TextInput(attrs={
        'id': 'datepicker',
        'class': 'form-control',
        'placeholder': 'Date of report',
        })) 
    class Meta:
        model = Report
        fields = ['report_date']

    def clean_report_date(self):
        return self.cleaned_data['report_date']

class ReportRemarksForm(forms.Form):
    remarks = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Enter remarks here',
        }))

    def clean_report_remarks(self):
        return self.cleaned_data['remarks']



    

lab_reports/views.py
import time


from django.shortcuts import get_list_or_404, get_object_or_404, render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views

from django.urls import reverse, reverse_lazy

from django.views import generic, View
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView, CreateView
from django.utils import timezone
from django.http import Http404
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.shortcuts import render

from django.forms import Textarea

from wkhtmltopdf.views import PDFTemplateView
import pdfkit

from .forms import TestForm, ReportDateForm, ReportRemarksForm, AuthenticationForm
from .models import Site, Report, Test

class LoginRequiredMixin(LoginRequiredMixin):
    login_url = '/login'


class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'lab_reports/dashboard.html'
    context_object_name = 'data'

    def get_queryset(self):
        return {
            "reports": Report.objects.recent_reports(6),
        }

class SiteListView(LoginRequiredMixin, generic.ListView):
    template_name = 'lab_reports/site/site_list.html'
    context_object_name = 'sites'

    def get_queryset(self):
        return Site.objects.all().order_by('description', 'location')

class SiteView(LoginRequiredMixin, DetailView):
    model = Site
    context_object_name = 'site'
    template_name = 'lab_reports/site/site_detail.html'

    def get_context_data(self, **kwargs):
        context = super(SiteView, self).get_context_data(**kwargs)
        context['reports'] = self.get_object().get_reports()
        return context

class ReportView(LoginRequiredMixin, DetailView):
    model = Report
    context_object_name = 'report'
    template_name = 'lab_reports/report/report_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ReportView, self).get_context_data(**kwargs)
        context['tests'] = self.get_object().get_tests()
        return context


class ReportDelete(LoginRequiredMixin, DeleteView):
    model = Report
    template_name = 'lab_reports/report/report_confirm_delete.html'
    def get_success_url(self):
        return reverse_lazy('lab_reports:site-detail', args = [self.get_object().site.id,], current_app='lab_reports')

class ReportCreate(View):
    template_name_field = 'lab_reports/report/report_form.html'
    def post(self, request, *args, **kwargs):
        site = Site.objects.get(pk=kwargs['site_id'])
        form = ReportDateForm(request.POST)
        if form.is_valid():
            report = Report.objects.create(site=site, report_date=form.cleaned_data['report_date'])
            report.save()
            return HttpResponseRedirect('/lab_reports/report/{}'.format(report.id))

    def get(self, request, *args, **kwargs):
        form = ReportDateForm()
        return render(request, 'lab_reports/report/report_form.html', {
        'form': form
        })

class ReportEditRemarksView(LoginRequiredMixin, View):
    template_name_field = 'report_remarks_form.html'

    def post(self, request, *args, **kwargs):
        form = ReportRemarksForm(request.POST)
        if form.is_valid():
            report = get_object_or_404(Report, pk=kwargs['report_id'])
            report.remarks = form.cleaned_data['remarks']
            report.save()
            return HttpResponseRedirect('/lab_reports/report/{}'.format(kwargs['report_id']))

    def get(self, request, *args, **kwargs):
        report = get_object_or_404(Report, pk=kwargs['report_id'])
        form = ReportRemarksForm(initial={'remarks': report.remarks })
        return render(request, 'lab_reports/report/report_remarks_form.html', {
            'form': form
            })


class TestAddView(LoginRequiredMixin, View):

    template_name_field = 'report_remarks_form.html'

    def post(self, request, *args, **kwargs):
        report_id = kwargs['report_id']

        report = Report.objects.get(pk=kwargs['report_id'])
        tests = Test.objects.filter(report__pk=kwargs['report_id']).order_by('description')
        form = TestForm(request.POST)
        report = get_object_or_404(Report, pk=report_id)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.report = report
            obj.save()
            return HttpResponseRedirect('/lab_reports/report/{}'.format(report_id))
        
    def get(self, request, *args, **kwargs):
        form = TestForm(initial={'measurement': 'ppm'})
        tests = Test.objects.filter(report__pk=kwargs['report_id']).order_by('description')
        return render(request, 'lab_reports/test/test_form.html', {
            'form': form,
            'tests': tests
            })

class TestDelete(LoginRequiredMixin, DeleteView):
    template_name='lab_reports/test/test_confirm_delete.html'
    model = Test
    def get_success_url(self):
        return reverse_lazy('lab_reports:report-detail', args = [self.get_object().report.id,], current_app='lab_reports')

class TestEdit(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        instance = get_object_or_404(Test, pk=kwargs['test_id'])
        report = Report.objects.get(pk=instance.report.id)
        tests = Test.objects.filter(report__pk=report.id).order_by('description')
        if request.method == "POST":
            form = TestForm(request.POST, instance=instance)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect('/lab_reports/report/{}'.format(report.id))

    def get(self, request, *args, **kwargs):
        instance = get_object_or_404(Test, pk=kwargs['test_id'])
        report = Report.objects.get(pk=instance.report.id)
        tests = Test.objects.filter(report__pk=report.id).order_by('description')
        form = TestForm(instance=instance)
        return render(request, 'lab_reports/test/test_form.html', {
            'form': form,
            'tests': tests
            })

class ReportPrintView(View):

    def get(self, request, *args, **kwargs):
        report = get_object_or_404(Report, pk=kwargs['report_id'])
        tests = report.get_tests()
        return render(request, 'lab_reports/report/report_print.html', {
            'report': report,
            'tests': tests
            })

class ReportDownloadView(LoginRequiredMixin, View):
    
    def get(self, request, *args, **kwargs):
        report = get_object_or_404(Report, pk=kwargs['report_id'])
        tests = report.get_tests()

        hostname = request.get_host()
        url = reverse('lab_reports:report-pdf', args = [kwargs['report_id'],], current_app='lab_reports')
        print(url)
        pdf_url = request.build_absolute_uri(url)
        print(pdf_url)
        pdf = pdfkit.from_url(pdf_url, False)
        response = HttpResponse(pdf,content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="{}_{}.pdf"'.format(report.report_date.strftime("%Y-%d-%m"), report.site.description)
        return response

class LoginView(auth_views.LoginView):
    template_name = '/registration/login.html'
    





            


        







    


    

lab_reports/templates/lab_reports/report/report_confirm_delete.html
{% extends 'lab_reports/sidebar.html' %} {% load static %} {% block content %}
<form style="margin-top: 25px;" action="" method="post">{% csrf_token %}
  <div class="form-group">
    <h3>Are you sure you want to delete report: <br><b> {{ object.report_date|date:"l M d, Y" }} - {{ object.site.description }} </b>?</h3>
    <input type="submit" value="Confirm" class="btn btn-block btn-large btn-danger" />
  </div>
</form>
{% endblock %}

lab_reports/templates/lab_reports/report/report_detail.html
{% extends 'lab_reports/sidebar.html' %} {% load static %} {% block content %}
<div class="container">
  <div class="row">
    <div class='col-lg-2'>
      <a class="btn btn-danger btn-block" href="{% url 'lab_reports:report-delete' report.id %}" class="top-menu">Delete Report</a>
    </div>
    <div class='col-lg-9'>
      <h3 class="text-center">Laboratory Report</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-2">
      <img src="{% static 'lab_reports/images/report_logo.png' %}" style="max-width: 160px;" />
    </div>
    <div class='col-lg-7'>
      <div class="address">
        Kem-Tek Chemical
        <br> 109 Cedarwood Drive Laflin, PA 18702
        <br> P.570-654-3487 F.570-654-4647
        <br> P.Sicilio@gmail.com
        <br>
      </div>
    </div>
    <div class='col-lg-3'>
      <div class="report-site-date text-right">{{report.report_date|date:"l M d, Y"|upper}}</div>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-lg-10">
      <div class="report-site-name">{{report.site.name}}</div>
      <div class="report-site-description">{{report.site.description}}</div>
      <div class="report-site-location">{{report.site.location}}</div>
    </div>
    <div class="col-lg-2">
      <a href="#" class="btn btn-block btn-lg btn-dark">Send</a>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <table class="table table-striped table-hover table-responsive-lg test-table">
        <thead>
          <tr>
            <th scope="col">Description</th>
            <th scope="col">Measurement</th>
            <th scope="col">Residuals</th>
            <th scope="col">Parameters</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          {% if tests %} {% for test in tests %}
          <tr>
            <td>{{ test.get_description_display }}</td>
            <td>{{ test.measurement }}</td>
            <td>{{ test.residuals }}</td>
            <td>{{ test.parameters }}</td>
            <td>
              <a href="{% url 'lab_reports:test-edit' test.id %}" class="btn btn-primary">Edit</a>
              <a href="{% url 'lab_reports:test-delete' test.id %}" class="btn btn-danger">Del&nbsp</a>
            </td>
            {% endfor %} {% else %}
            <td colspan="5">There are no tests in this report</td>
            {% endif%}
          </tr>
          <tr>
            <td colspan="5">
              <div class="card" style="margin-top: 20px; width: 100%;">
                <div class="card-body">
                  <h3 class="card-title">Remarks <a href="{% url 'lab_reports:report-edit-remarks' report.id %}" class="btn btn-warning">Edit</a></h3> {% if report.remarks %}
                  <p class="card-text">{{ report.remarks }}</p>
                  {% else %}
                  <p class="card-text">No remarks</p>
                  {% endif %}
                </div>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-2">
      <a class="btn btn-success btn-block" href="{% url 'lab_reports:test-add' report.id %}" class="top-menu">Add Test</a>
      <a class="btn btn-info btn-block" href="{% url 'lab_reports:report-download' report.id %}" class="top-menu">PDF</a>
    </div>
  </div>
</div>
{% endblock %}

lab_reports/templates/lab_reports/report/report_form.html
{% extends 'lab_reports/sidebar.html' %} {% load static %} {% block content %}
<div class="row">
  <div class="col-lg-4">
    <div class="card">
      <div class="card-header">
        <h4>Report Date</h4>
      </div>
      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %} {% for field in form %}
        <div class="form-group form-control-lg">
          <div class="row">
            <div class="col">
              {{ field.label_tag }}
            </div>
            <div class="col">
              {{ field }}
            </div>
          </div>
        </div>
        {% endfor %}
        <button class="btn btn-primary btn-lg" style="margin: 5% 5% 5% 10%; width: 80%;" type="submit" value="Submit">Submit</button>
      </form>
    </div>
  </div>
</div>
<script>
  $( function() {
    $( "#datepicker" ).datepicker();
  } );
  </script>
{% endblock %}

lab_reports/templates/lab_reports/report/report_print.html
{% load static %} {% block content %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../../../favicon.ico">
  <title>Kem-Tek Chemical</title>
  <link rel="stylesheet" type="text/css" href="{% static 'lab_reports/css/simple-sidebar.css' %}" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>

<body>
  <div class="container">
    <div class="row">
      <div class='col-md-2'>
      </div>
      <div class='col-md-9'>
        <h3 class="text-center">Laboratory Report</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-3 pull-left">
        <img src="{% static 'lab_reports/images/report_logo.png' %}"/>
      </div>
      <div class='col-lg-5'>
        <div class="address">
          Kem-Tek Chemical
          <br> 109 Cedarwood Drive Laflin, PA 18702
          <br> P.570-654-3487 F.570-654-4647
          <br> P.Sicilio@gmail.com
          <br>
        </div>
      </div>
      <div class='col-lg-3'>
        <div class="report-site-date text-right">{{report.report_date|date:"l M d, Y"|upper}}</div>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-lg-10">
        <div class="report-site-name">{{report.site.name}}</div>
        <div class="report-site-description">{{report.site.description}}</div>
        <div class="report-site-location" style='margin-bottom: 30px;'>{{report.site.location}}</div>
      </div>
    </div>
    <div class="row">
      <table class="table table-striped table-hover test-table">
        <thead>
          <tr>
            <th scope="col">Description</th>
            <th scope="col">Measurement</th>
            <th scope="col">Residuals</th>
            <th scope="col">Parameters</th>
          </tr>
        </thead>
        <tbody>
          {% if tests %} {% for test in tests %}
          <tr>
            <td>{{ test.get_description_display }}</td>
            <td>{{ test.measurement }}</td>
            <td>{{ test.residuals }}</td>
            <td>{{ test.parameters }}</td>
            {% endfor %} {% else %}
            <td colspan="4">There are no tests in this report</td>
            {% endif%}
          </tr>
          <tr style="background-color: white">
            <td colspan="5">
              <div class="card" style="margin-top: 20px; width: 100%;">
                <div class="card-body">
                  <h3 class="card-title">Remarks</h3> {% if report.remarks %}
                  <p class="card-text">{{ report.remarks }}</p>
                  {% else %}
                  <p class="card-text">No remarks</p>
                  {% endif %}
                </div>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</body>

</html>
{% endblock %}

lab_reports/templates/lab_reports/report/report_remarks_form.html
{% extends 'lab_reports/sidebar.html' %} {% load static %} {% block content %}
<div class="row">
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header">
        <h4>Report Remarks</h4>
      </div>
      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %} {% for field in form %}
        <div class="form-group form-control-lg">
          <div class="row">
            <div class="col">
              {{ field }}
            </div>
          </div>
        </div>
        {% endfor %}
        <button class="btn btn-primary btn-lg" style="margin: 5% 5% 5% 10%; width: 80%;" type="submit" value="Submit">Submit</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}